### ISSUE TITLE
關於info的stars標籤

### ISSUE THREAD

**Issue by yuanqiuye** [JAVClub/fetcher#6]
建議如果stars的資訊為空，可以將其自動填寫為：
stars: [
  素人
]
因為素人系列的都沒有stars標籤ww

**Comment by isXiaoLin** [comment]
这样，了解了，有空加上hhh

**Comment by isXiaoLin** [comment]
Fixed in https://github.com/JAVClub/core/commit/b5237dc5d8a3e98d390109ffd6f8204b414b17e7

**Comment by yuanqiuye** [comment]
突然發現fetcher的判定規則還是照舊啊ww 看到空stars就擋，想說怎麼還是沒看到素人片XD

**Comment by isXiaoLin** [comment]
忘了 fetcher 里面还写死了hhh，已修改
