### ISSUE TITLE
希望增加本地自定义视频导入fetcher进行处理功能

### ISSUE THREAD

**Issue by fbbang** [JAVClub/fetcher#9]
如题，当前fetcher是通过爬取种子信息导入qb，通过qb下载完成来触发fetcher处理视频的动作，手动发进去本地视频并不会处理。希望开放手动添加视频并触发fetcher去处理视频，这样视频可选来源范围比较广。

**Comment by isXiaoLin** [comment]
导入已有视频不说不可能，只说工作量比较大，因为大部分视频的文件名都是不规则的，要从中识别出番号需要一定处理

如果希望拓宽视频来源可以选择自行编写新的 driver

**Comment by kalagxw** [comment]
https://rsshub.app/2048/bbs/5?filter=%E6%96%B0%E7%89%87%E5%8E%9F%E6%A1%A3%E9%A6%96%E5%8F%91 ，这个看看能写driver吗，文件可以用大小过滤，合集也基本都是单文件

**Comment by fbbang** [comment]
1
